# Generated by Django 5.0.6 on 2024-06-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='staus',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
    ]
