# Generated by Django 5.0.6 on 2024-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_alter_lesson_course_alter_task_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ManyToManyField(blank=True, null=True, to='LMS.customuser'),
        ),
    ]
