# Generated by Django 5.0.6 on 2024-06-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_alter_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LMS.task_done'),
        ),
    ]
