# Generated by Django 5.0.7 on 2024-07-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_alter_like_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
