# Generated by Django 5.0.7 on 2024-07-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_remove_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
    ]
