# Generated by Django 5.0.7 on 2024-07-19 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_remove_comment_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='creator',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('comment', 'user')},
        ),
    ]
