# Generated by Django 5.0.6 on 2024-07-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_remove_task_creator_task_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_done',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='LMS.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_task', to='LMS.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('notdone', 'Not Done'), ('done', 'Done')], default='notdone', max_length=50),
        ),
        migrations.CreateModel(
            name='Course_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='LMS.course')),
                ('users_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to='LMS.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='LMS.task')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to='LMS.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Task_Done',
        ),
    ]
