# Generated by Django 5.0.7 on 2024-07-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_rename_creator_like_user_alter_like_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='task',
        ),
    ]
