# Generated by Django 5.0.6 on 2024-07-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_remove_task_creator_task_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_done',
        ),
        migrations.AddField(
            model_name='task_done',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='task_done_media/'),
        ),
        migrations.AddField(
            model_name='task_done',
            name='mark',
            field=models.CharField(choices=[('0', 'Не оценено'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='task_done',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.lesson'),
        ),
    ]
