# Generated by Django 5.0.6 on 2024-07-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_remove_task_task_done_task_done_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dead_line',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
