# Generated by Django 5.0.7 on 2024-07-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_rename_post_comment_task'),
        ('LMS', '0010_alter_course_creator'),
    ]

    operations = [
    ]
