# Generated by Django 5.0.7 on 2024-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_merge_20240726_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
