# Generated by Django 5.0.6 on 2024-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_alter_task_done_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_done',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
