# Generated by Django 5.0.7 on 2024-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель'), ('student', 'Студент')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
